language: node_js
node_js: '9'
services:
- postgresql
before_script:
- psql -c 'create database palette_picker_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: LMMxwCD2oxOEtLFhbNO/sBs56Qhm06jJJ9Xcl1opcXf6O+Tj5b2Dk+dmxIqz32bmRgYU2PIQMIkWsjdiRfW0rpLpKVi2ELebYq3b1d7JV9t+pzCAnw2QV6DhL4198bwCKHe6GzgW9Bsgnawy4w3WtpXJSQtvnGYswFpmKwG253R/z6W2N7uaP8oYB40aby3KvOI8qqd4LyNGqedl66xKr0aVDbIwDVhkMVevnAGGKE55iD5RI/vplGvgWcS5/nhChsQuEsj89hkjp/0fB2XFKibNwRIYd4AUKmCdSxUvY+Lie6gvO4VDVl8J8MLPTcw0ZcUivdRODzclc7LeZao/AbZRtgdJM7szJiMP9gIjnGdo7peEgZpc35E6oaX4FACIOFHr2pz6de1HDHiPr8+KUwjzITk3aBzvacqKrSI0ITQ5AlcOLN6I+Jw2KTU30NRUAEsIbtueg/2MbTsHRWqZHdEfcjVKrujAKmY9mZOs2fU7RGvR+T1A31Ped5+LUpTr85WZjUbJ5odzE8B+bgLjkiKPCo0fspehwzOmJA/vzUmCzgOItB/ZcHu+1UVdna7nouRW77GKfgLRf5xc4/ZcsijUyCfbuOFmWaNngBBZ0GP9PQm7ve7sMa9T6zW/utMrxZH2bonWhB2QshowTgc2mL8h7rPLnHTmzyQDLu91qAs=
  app: palette-picker-jaredeklin
